### ISSUE TITLE
Update not appearing randomly in some servers

### ISSUE THREAD

**Issue by jmfergeau** [Moenus/wp-gitlab-updater#10]
Hi there. Sorry to bother again.. But for some reason it seems the updater doesn't work anymore again, similar to issue #7.

- I followed the instructions step by step.
- It's the right token and the access is still active.
- When trying to get to the URL of the api using a browser, I get the versions as expected.

Actually the script worked once... But only once. (I remember there was even a glitch on the update page. The picture of the theme was "missing" what picture file wordpress is looking for, here?) 
But when it happened, I remember the theme was in a folder with a different name than the theme (it was "duenarevival"). And when it updated, it put everything in a new folder with the right name (which was "duena"), while keeping the old version "duenarevival" in its folder. For now I activated the theme with the folder "duena" and deleted the other one. Maybe it's the cause of the problem?

In case you wanna check, [here's the repository of the theme with the updater](https://github.com/maxlefou/DuenaRevivalTheme).

**Comment by florianbrinkmann** [comment]
Hi @maxlefou,

no worries, thanks for opening the issue :)

And thanks for the repo link. I installed the theme in a `duena` folder on a test server, manually set the version to 3.0.0, got an upgrade notification with the correct screenshot and was able to install it.

I think the reason for your missing image might be the different folder name. I guess WP shows the image from your installed theme, but searched for it in the `duena` folder that did not exist at that moment. Maybe it would have worked if you had set the slug to `duenarevival` in the params of the updater call.

Maybe you could manually set the version in the `style.css` to something lower than 3.1.0 and check if it works correctly now with the `duena` folder (or release a new version of the theme on GitLab :) ).

Best,
Florian

**Comment by jmfergeau** [comment]
thanks for the reply. :)

Wait, so it worked perfectly for you then? oO So that means there's a problem with the server I use.

For now I have a test wordpress on it that still has the 3.0.0 but it still doesn't see the update. I checked the php logs but couldn't see anything. do you know if there's a way to activate a debug mode or something on wordpress so i can track what's going on?

**Comment by florianbrinkmann** [comment]
Yes, it worked for me. There is a debug mode (https://wordpress.org/support/article/debugging-in-wordpress/), but I think there will nothing appear, too.

I modified the `theme-updater.php` with `error_log()` calls, so you should get messages along the process of searching for an update: https://gist.github.com/florianbrinkmann/b14bfbcf20b6509a0d414420124299d3 (I did not test it, but should work).

If you enable the `WP_DEBUG` and `WP_DEBUG_LOG` via the `wp-config.php` (described in the article linked above), you should get messages in the `wp-content/debug.log` file, that tell you how far the plugin came while searching for a theme update.

**Comment by jmfergeau** [comment]
i replaced the file and did what you said. Sadly no errors reported :/ I really don't know what's wrong... I'm gonna check with my service. (it's Gandi Simple Hosting for info, in case someone else gets the problem too)

Thanks again for your time. If i found anything i'll report here :) If it just affects me and not the other users, it's ok and all good ^^

**Comment by jmfergeau** [comment]
.... ok now i'm super confused.
It suddenly worked again! 

What I did? just putting back WP_DEBUG to false! Like it was before I started doing the manips with your edited php! (though, I kept the php you did.)

I'm going to be crazy :o 

(and btw the picture is right now, which confirms what you said about it :p )

**Comment by jmfergeau** [comment]
... And the time I get back reporting (without updating), I go back to the wp dashboard... and the update disappeared!

(┛◉Д◉)┛彡┻━┻

**Comment by florianbrinkmann** [comment]
Hm, I think there was something with that WordPress caches the result of the update check, so it may be the case that it does not run the update check every time you visit the updates page (not sure about that). Why the update disappeared: no idea, could you try to turn on the debug logging again and check if something is logged while checking for updates a few times (with some time between it, for the case if there is a cache).

**Comment by jmfergeau** [comment]
I redid like before and everything happened exactly like earlier. To resume it, like this:

1. No updates appearing.
2. I enable wp_debug.
3. No updates appearing.
4. I disable wp_debug
5. Update appears. I don't touch it.
6. I wait around 3 or 4 minutes, doing nothing.
7. Update disappears.

To me it doesn't make sense at all :s And the worst part, debug doesn't report anything related to the updater and doesn't even make a log file even with wp_debug_log

Even worse, i did all of this a second time, and this time the update didn't appeared at all.

**Comment by florianbrinkmann** [comment]
Thanks for giving it a try again! Do you have the chance to test it on another server?

**Comment by jmfergeau** [comment]
sadly I only have that one. I don't dare trying in local since in the issue #7 the problem was exactly because it was in local.

In my personnal case it's ok though. I don't mind updating manually for me, as long as other users can have the update. :p

**Comment by florianbrinkmann** [comment]
All right. I tested it again on my server, this time not updating directly to see if the update disappears after some time, but I cannot reproduce that. Clicking around in the backend for some time but the update notification stays there and I can update it.

So I guess you are right, and it is something with your host. If their service comes back to you with something helpful, would you post it here?

**Comment by jmfergeau** [comment]
Sure thing. I'll see what I can do ;)

**Comment by jmfergeau** [comment]
Ok I got feedback from Gandi.

For some odd reason, it works perfectly for them. The only difference between what they used to try and what i have is mysql being 5.7 for them and 5.5 for me. But I don't think your script actually calls for the db. Does it?

I'll still keep trying and will post if i get any more infos.

**Comment by florianbrinkmann** [comment]
Hey,

thanks for coming back with the feedback! Indeed, that sounds strange. No, the plugin is not calling the DB, so — theoretically — that should not make a difference 🤔

Is it possible for you to update MySQL to .7 to try if this fixes it for you (for whatever reason)?

Best,
Florian

**Comment by jmfergeau** [comment]
I'll see if i can. Will report if i get any news ;)

**Comment by jmfergeau** [comment]
I got some more news from the support.

Some minutes ago, magically, the update appeared in one of my wordpress. 5 minutes later, wihtout touching it, I recheck the updates. It disappeared and the line `WARNING: [pool www] server reached max_children setting (2), consider raising it` appeared in the fpm.log of my server at the same time I did the check. (the same line is regulary spammed in the file at other times too, though. Probably when wordpress does its auttomatic update checks)

The support explained me that I have a server instance that has only 2 max_children process enabled for php. When they did the test, they were having 6 in their own server. Maybe that's why it doesn't work properly for me and works for the others.

The support advised me to invest in a bigger instance to add at least 2 more children php process to check if the problem still occurs. But sadly I can't invest more than I already do so i can't try. (I'd try locally with my wamp, but I heard the script doesn't work when used in localhost) Anyway, i'm pretty sure the problem comes from here.

Feel free to try if you have a test server where you can change the max_children value.

**Comment by florianbrinkmann** [comment]
> The support advised me to invest in a bigger instance to add at least 2 more children php process to check if the problem still occurs.

Wow, that sounds like you should switch to another web host as quick as possible! Besides of that, it sounds like that could be the reason for your issues.

I read this article (https://serverpilot.io/docs/how-to-change-the-php-fpm-max_children-setting) with a few background info. If I understand it correctly, 2 seems to mean that – if WordPress runs a process that takes a little longer, like checking for updates (at least I can imagine this is a process that takes its time), there only needs to be two parallel other PHP tasks in parallel to raise the limit.

I was not able to find a quick solution to decrease the number on my local machine, so I cannot verify that, but if I understood the meaning of the value right, 2 sounds like a very low value (the serverpilot mentions 20 as a default).

Best,
Florian

**Comment by jmfergeau** [comment]
True thing, i'd have to change, or increase my instance. The one I have is actually at the lowest settings cuz it's the cheapest. For what I use and do, it's pretty much enough for me. Even, despite what they say, even with 3 wordpresses inside, the only problem i even got so far with my instance is your script not updating. That's all. So, in my case, I don't think I really need to update. Or even to change. Unless I find something better for the same price or lower. I doubt there is but i'll check that out just in case.

(actually, gandi uses virtual machines to make server instances, and i bet there's several of these instances in one physical server. That would explain why max_children is so low for these ones)

The link you provided confirms the theory I had. I'm now sure at 99% that the max_children setting of my instance is the problem. Maybe it's safe to close this ticket now. I'm glad we finally figured out. ^^

**Comment by florianbrinkmann** [comment]
> I'm glad we finally figured out. ^^

I am, too! :)

Regarding hosters: Maybe take a look at https://uberspace.de/en/. I host a few sites there and am very happy with them :)

**Comment by jmfergeau** [comment]
Thanks for the tip! I'd prefer servers based in france (bandwith matters :p ) but i'll definitely check that out :)

EDIT: Oh they're based in Germany but have servers in france. Great ^^

**Comment by florianbrinkmann** [comment]
Hm, where did you read this with servers in france? As far as I know, they just have servers in Germany.

> I'd prefer servers based in france (bandwith matters :p )

Yeah, I guessed that, but after seeing that you are in France, I thought, well, that is not so far away from Germany, so that should not make a big difference ;)

**Comment by jmfergeau** [comment]
I've seen that on the FAQ, the FRA2 and the city called Francfort-something led me to think it was in france :p though, they said otherwise somewhere else in their website. Oh well... :p

**Comment by florianbrinkmann** [comment]
Ah okay :) No, FRA is a short form of Frankfurt :)
