### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by vipii** [Moenus/wp-gitlab-updater#12]
Is it possible this plugin is not working anymore?

**Comment by florianbrinkmann** [comment]
Hi @vipii,

what does not work for you exactly? I just tried it as a WP plugin and successfully updated a plugin from GitLab with it.

Best,
Florian

**Comment by AMCodeHub** [comment]
I tried it as a WP plugin and with files included in the plugin and I can't get either to work. 

GitHub Updater works with my plugins, and I deactivated it before trying your plugin. I confirmed that I can download my archive.zip if I use this URL: $gitlab_url/api/v4/projects/$repo/repository/archive.zip?private_token=$access_token

however, my repo name didn't work, but my repo ID did work with that api request. I tried using the repo id in the plugin field and in the attribute settings when trying to embed the files in my plugin. 

How are you checking to see if there is an update available? Are you using the version number in the comment section of the plugin?

**Comment by AMCodeHub** [comment]
@florianbrinkmann I now see that it is checking the gitlab tags to identify if there is an update available. What tag specifically triggers the available update? How often does it make an API call to check for available updates?

**Comment by AMCodeHub** [comment]
@florianbrinkmann I now see that it is checking the gitlab tags to identify if there is an update available. What tag specifically triggers the available update? How often does it make an API call to check for available updates?

**Comment by florianbrinkmann** [comment]
@AMCodeHub It checks the latest tag. When the tag is a version number that is higher than the current version of the plugin/theme, the update is triggered. The updater hooks into the core update system, so it should check for new updates when WordPress checks for plugin/theme updates.
