### ISSUE TITLE
The plugin is at the latest version.

### ISSUE THREAD

**Issue by AmityTek** [Moenus/wp-gitlab-updater#17]
Anyone have an idea ?

I have this error but I updated all version in my plugin and the tags is different is greater than the old one

![image](https://user-images.githubusercontent.com/18656702/159686122-48da21f4-a383-4c27-a85f-11a30deebd73.png)

![image](https://user-images.githubusercontent.com/18656702/159686181-db04e693-3a8c-494f-a5d2-8597663a7325.png)

**Comment by florianbrinkmann** [comment]
Hi,

maybe the code you added to always check for new versions is the issue, does it work without it?

**Comment by AmityTek** [comment]
If you are talking about my old issue, yes I already removed it because it wasn't workin correctly ...

**Comment by AmityTek** [comment]
Now I deleted the old plugin wp-gitlab-updater and put your clean plugin, but wordpress doesn't  triggers/see when I create a new tag.
It's very strange .. do you have a solution for that ?

**Comment by florianbrinkmann** [comment]
> Now I deleted the old plugin wp-gitlab-updater and put your clean plugin

What do you mean with that? Have you correctly configured the updater like written in the readme?

WP does not always check for updates. You can use the force check button on the update screen to do that.

**Comment by AmityTek** [comment]
Ok good I made an investigation and it's ok now ! 
thanks
