### ISSUE TITLE
Commited but won't show up in wp updates.

### ISSUE THREAD

**Issue by edemir206** [Moenus/wp-gitlab-updater#6]
Hi,
I just found your plugin and installed, but the commited update won't show up on plugins updates.

Do I need to change something on the plugin files other than just commit to gitlab and configure token/url/repo ?

**Comment by florianbrinkmann** [comment]
Hi!

Have you created a Git tag for the new version (the plugin checks for the tags, not every commit)?

Florian

**Comment by edemir206** [comment]
Do you mean any of this tag that is present on readme.txt ? 

=== Pesquisa Global UFSM ===
Tags: search, multisite, widget, multilingual, global, shortcode
Requires at least: 3.0
Tested up to: 4.9.1
Stable tag: 1.2.15

**Comment by florianbrinkmann** [comment]
No, a tag to mark a specific state of the project in Git (for example, for releases). You can find the tags feature in GitLab here (Screenshot from an overview page of a GitLab repo):

![gitlab-tags](https://user-images.githubusercontent.com/2310924/34209475-979ab368-e592-11e7-8df1-7563c3e102a3.PNG)

Just create a tag (can be equal to the plugin version in the readme.txt), and if the tag number is larger than the version that is installed on the WP install, you will get the updated version from GitLab :)

**Comment by edemir206** [comment]
Thanks for help, 

It works now.

**Comment by florianbrinkmann** [comment]
Great to hear that! :)
