### ISSUE TITLE
Doesn't working

### ISSUE THREAD

**Issue by adrianbrs** [Moenus/wp-gitlab-updater#7]
I did everything right, I included in my theme with correct fields, but it doesn't work. I tested put the url directly and it returns tag data, but no updates shown in my wordpress administration panel.

**Comment by florianbrinkmann** [comment]
Hi!

Just for safety: you bundled the two files into your theme, included it into `functions.php` or similar, and called `new Moenus\GitLabUpdater\ThemeUpdater()` with the needed params? And you created a tag with a higher number on GitLab than the installed theme version?

Thanks,
Florian

**Comment by adrianbrs** [comment]
Yes, I tried to install the plugin too, but no results.
I tried with and without the "v" before the version in both gitlab tag and theme version, nothing showing up.
![screenshot_1](https://user-images.githubusercontent.com/20914057/35230249-ae867748-ff7c-11e7-8930-c5cd11c95c8f.png)
![screenshot_2](https://user-images.githubusercontent.com/20914057/35230244-ada036a2-ff7c-11e7-9663-e5936fbaad23.png)
![screenshot_3](https://user-images.githubusercontent.com/20914057/35230246-adda892e-ff7c-11e7-9994-92c1e8479d9e.png)
![screenshot_4](https://user-images.githubusercontent.com/20914057/35230247-ae2913be-ff7c-11e7-9989-6ee9874653d7.png)
_(access token is correctly, with Postman I am receiving correct data from GitLab)_

Maybe I'm doing something wrong, but I don't know what is :/
Thanks!!!

**Comment by adrianbrs** [comment]
Problem solved!
I think this don't work in localhost, because now in my hosted website, it's working perfectly!

Thanks for your support! 😄

**Comment by florianbrinkmann** [comment]
Great to hear that, thanks for your feedback! :) I will test it locally and try to find out why it does not work there.
