### ISSUE TITLE
error 401 when trying to fetch tags

### ISSUE THREAD

**Issue by jmfergeau** [Moenus/wp-gitlab-updater#9]
Hi. I'm trying to bundle this script inside my theme, i followed all the instructions of your repo, but I'm getting the same problem as issue #7 . Except the website where i'm trying it is not in localhost and is hosted outside. I found something odd though.

When I try the command `curl --request GET --header` with the token and the url, I get the tags fetched as expected:
```
max@VirtualBox:~$ curl --request GET --header "PRIVATE_TOKEN: XXXXXXXXXXX" https://gitlab.com/api/v4/projects/xxxxxxxx%2Fxxxxxxxxx/repository/tags/
[{"name":"2.2.1","message":"xxxxxxxx!","target":"XXXXXXXXXXX","commit":{"id":"XXXXXXXXXXXXX","short_id":"xxxx",...
```

But when I try the curl command using the url that the script uses in its code (line 54 in updater-base.php), i get this:
```
max@VirtualBox:~$ curl https://gitlab.com/api/v4/projects/xxxxxxxx%2Fxxxxxxxxx/repository/tags/?private_token=XXXXXXXXXXX
{"message":"401 Unauthorized"}
```

It's probably an error with gitlab but i don't understand it and it looks like it's preventing the script to work and fetch update. :/ any idea of what's wrong?

**Comment by florianbrinkmann** [comment]
Hi @maxlefou,

I just tried the URL format with the `private_token` param you posted and I correctly get the tag and no 401. Are you sure that the project name and the token are correct? Have you tried to load the URL directly in the browser?

Best,
Florian

**Comment by jmfergeau** [comment]
yes, i tried all of this and the only way i got the tags correctly is by using the `curl --request GET --header` command. All the others gives me 401, including with the browser 

![Capture](https://user-images.githubusercontent.com/6705075/59586302-e6c21b00-90e2-11e9-9437-38aa5e1eed8e.JPG)

read_repository and read_registry are enabled, as mentionned in the instructions. I tried making another token just for test, but still 401. i don't get what's wrong, everything is done using direct copypaste so there can't be errors :(

**Comment by jmfergeau** [comment]
I made you a token so you can try (it's gonna end in the 20th so feel free to ask another one if needed. It's a public project anyway):
```
repo: maxlefou%2FDDuenaRevivalTheme
token: p3uNd9xdLf-Ftam6eeGe
```

**Comment by florianbrinkmann** [comment]
Yes, getting an 401 with that, too. Just to make sure: You created the key here: https://gitlab.com/profile/personal_access_tokens

With the `api`, `read_registry` scopes?

**Comment by jmfergeau** [comment]
darnit! That's why it wasn't working! There's two kinds of tokens and of course i was on the wrong one. (the one in settings/repository)

Thanks for the directions. Gitlab should be really less confusing with tokens. :| I suggest you put this url in the instructions too just in case someone else gets confused as well.

Thanks again for the help, now it should work. ^^

**Comment by florianbrinkmann** [comment]
You’re welcome, happy to hear that :) Yes, will add the URL to the readme, that’s a good idea. I’ll close the issue for now, feel free to reopen it if you have further problems with that :)

**Comment by florianbrinkmann** [comment]
Added the link
